name = "misub"
compatibility_date = "2024-06-13"

[[kv_namespaces]]
binding = "MISUB_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # 请确保这里是你正确的 KV ID
preview_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy" # 请确保这里是你正确的预览 KV ID